/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisteecle;

import com.sun.javafx.scene.control.skin.ComboBoxPopupControl;
import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.lang.Class;

/**
 *
 * @author Jesùs de Gran Poder
 */
public class cambio_contra extends javax.swing.JFrame {

    conexion cc = new conexion();
    Connection cn = cc.conexion();

    /**
     * Creates new form cambio_contra
     */
    public cambio_contra() {
        initComponents();
        this.setLocationRelativeTo(null);

        this.usuario.setVisible(false);
        this.ul.setVisible(false);
        this.correo.setVisible(false);
        this.cl.setVisible(false);
 
         

    }

    
  
    public void validar_datos() {
        int resultado = 0;
        String cor = correo.getText();
        String usu = usuario.getText();
        
        String SQL1 = " SELECT * FROM usuario WHERE usuario='" + usu + "'";
        String SQL2 = " SELECT * FROM persona WHERE correo='" + cor + "'";
        try {
            if (combo.getSelectedItem() == "USUARIO") {
                Statement st = cn.createStatement();
                ResultSet rs = st.executeQuery(SQL1);
                if (rs.next()) {
                    resultado = 1;
                    if (resultado == 1) {
                        cambio_contr2 c2 = new cambio_contr2();
                        c2.setVisible(true);
                       
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Acciòn no Permitido, el Usuario no esta Registrado...");
                }

            } else {
                if (combo.getSelectedItem() == "CORREO ELECTRONICO") {
                    Statement st = cn.createStatement();
                    ResultSet rs = st.executeQuery(SQL2);
                    if (rs.next()) {
                        resultado = 1;
                        if (resultado == 1) {
                            cambio_contr2 c2 = new cambio_contr2();
                            c2.setVisible(true);
                          
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Acciòn no Permitido, este Correo Electronico no pertenece a ningun Usuario...");
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de Conexiòn");
        }

    }
    
     

    public void mostrar_combo() {
        if (combo.getSelectedIndex() == 0) {
            this.usuario.setVisible(false);
            this.ul.setVisible(false);
            this.correo.setVisible(false);
            this.cl.setVisible(false);

        } else {
            if (combo.getSelectedIndex() == 1) {
                this.usuario.setVisible(true);
                this.ul.setVisible(true);
                this.correo.setVisible(false);
                this.cl.setVisible(false);
            } else {
                if (combo.getSelectedIndex() == 2) {
                    this.usuario.setVisible(false);
                    this.ul.setVisible(false);
                    this.correo.setVisible(true);
                    this.cl.setVisible(true);
                }
            }
        }

    }
    
    private void mostrar(){
        temporal_cambio t1 = new temporal_cambio();
        JOptionPane.showMessageDialog(null, "CONTENIDO = " + t1.getUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        registrar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        cl = new javax.swing.JLabel();
        ul = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        combo = new javax.swing.JComboBox<>();
        correo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        registrar.setFont(new java.awt.Font("BankGothic Lt BT", 1, 11)); // NOI18N
        registrar.setText("REGISTRAR");
        registrar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                registrarStateChanged(evt);
            }
        });
        registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarMouseClicked(evt);
            }
        });
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        cancelar.setFont(new java.awt.Font("BankGothic Lt BT", 1, 11)); // NOI18N
        cancelar.setText("CANCELAR");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        cl.setFont(new java.awt.Font("BankGothic Lt BT", 0, 14)); // NOI18N
        cl.setText("Correo electronico");

        ul.setText("USUARIO");

        usuario.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                usuarioCaretUpdate(evt);
            }
        });

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NULL", "USUARIO", "CORREO ELECTRONICO", " " }));
        combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboItemStateChanged(evt);
            }
        });
        combo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                comboMouseDragged(evt);
            }
        });
        combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                comboMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                comboMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                comboMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                comboMouseReleased(evt);
            }
        });
        combo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboKeyPressed(evt);
            }
        });

        jLabel1.setText("Escoger");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(cancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(cl)
                                .addGap(32, 32, 32)
                                .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(ul)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)))))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ul, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cl)
                    .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
//        cambio_contr2 cm = new cambio_contr2();
        validar_datos();
//        cm.usuario2 = usuario.getText();
//        cm.correo2 = correo.getText();

    }//GEN-LAST:event_registrarActionPerformed

    private void comboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboKeyPressed

    }//GEN-LAST:event_comboKeyPressed

    private void comboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMouseClicked

    }//GEN-LAST:event_comboMouseClicked

    private void comboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMouseEntered

    }//GEN-LAST:event_comboMouseEntered

    private void comboMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMouseExited

    }//GEN-LAST:event_comboMouseExited

    private void comboMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMousePressed

          }//GEN-LAST:event_comboMousePressed

    private void comboMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMouseReleased

    }//GEN-LAST:event_comboMouseReleased

    private void comboMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMouseDragged
    }//GEN-LAST:event_comboMouseDragged

    private void comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboItemStateChanged
        mostrar_combo();
    }//GEN-LAST:event_comboItemStateChanged

    private void registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarMouseClicked

    }//GEN-LAST:event_registrarMouseClicked

    private void usuarioCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_usuarioCaretUpdate
       temporal_cambio t1 = new temporal_cambio();
       t1.setUsuario(usuario.getText().trim());
       t1.setCorreo(correo.getText().trim());
    }//GEN-LAST:event_usuarioCaretUpdate

    private void registrarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_registrarStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cambio_contra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cambio_contra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cambio_contra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cambio_contra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cambio_contra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel cl;
    private javax.swing.JComboBox<String> combo;
    public static javax.swing.JTextField correo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registrar;
    private javax.swing.JLabel ul;
    public static javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
