/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisteecle;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Zambrano
 */
public class recodar_1 extends javax.swing.JFrame {

    conexion cc = new conexion();
    Connection cn = cc.conexion();

    /**
     * Creates new form recodar_1
     */
    public recodar_1() {
        initComponents();
        this.setLocationRelativeTo(null);
        pn.setVisible(false);
        ap.setVisible(false);
        ce.setVisible(false);
        us.setVisible(false);
        nombre.setVisible(false);
        apellido.setVisible(false);
        correo.setVisible(false);
        usuario.setVisible(false);
//        buscar.setEnabled(false);
    }

    public void mostrar_combo() {
        if (combo.getSelectedItem() == "USUARIO") {
            pn.setVisible(true);
            ap.setVisible(true);
            ce.setVisible(true);
            us.setVisible(false);
            nombre.setVisible(true);
            apellido.setVisible(true);
            correo.setVisible(true);
            usuario.setVisible(false);
        } else {
            if (combo.getSelectedItem() == "CORREO ELECTRONICO") {
                pn.setVisible(true);
                ap.setVisible(true);
                ce.setVisible(false);
                us.setVisible(true);
                nombre.setVisible(true);
                apellido.setVisible(true);
                correo.setVisible(false);
                usuario.setVisible(true);
            }
        }
    }

    public void buscar() {
        int resultado = 0;
        int resultado1 = 0;
        String usu = usuario.getText();
        String nom = nombre.getText();
        String apel = apellido.getText();
        String corr = correo.getText();
        String SQL = " SELECT usuario FROM usuario WHERE id_usu = (SELECT id_usu FROM persona WHERE correo = '" + corr + "' AND nombre1 = '" + nom + "' AND apellido1 = '" + apel + "')";
        String SQL1 = " SELECT correo FROM persona WHERE id_usu = (SELECT id_usu FROM usuario WHERE usuario = '" + usu + "') AND nombre1 = '"+ nom +"' AND apellido1 = '"+apel+"' ";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(SQL);
                Statement st1 = cn.createStatement();
            ResultSet rs1 = st1.executeQuery(SQL1);

            if (combo.getSelectedItem() == "USUARIO") {
                if (rs.next()) {
                    resultado = 1;
                    if (resultado == 1) {
                        JOptionPane.showMessageDialog(null, "Su Usuario es: " + rs.getString(1));
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Usuario no Registrado");
                }
            } else {
                if (combo.getSelectedItem() == "CORREO ELECTRONICO") {
                    if (rs1.next()) {
                        resultado1 = 1;
                        if (resultado1 == 1) {
                            JOptionPane.showMessageDialog(null, "Su correo electronico es: " + rs1.getString(1) + ", y pertenece al Usuario " + usu);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "El correo electronicono no existe");
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Usuario no Registrado");

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        pn = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        ap = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        usuario = new javax.swing.JTextField();
        ce = new javax.swing.JLabel();
        us = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NULL\t", "USUARIO", "CORREO ELECTRONICO", " " }));
        combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboItemStateChanged(evt);
            }
        });

        jLabel1.setText("Elegir");

        pn.setText("Primer Nombre");

        ap.setText("Apellido Paterno");

        ce.setText("Correo Electronico");

        us.setText("Usuario");

        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ce)
                            .addComponent(ap)
                            .addComponent(us))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(usuario))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(correo))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pn)
                        .addGap(37, 37, 37)
                        .addComponent(nombre)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)
                        .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buscar)
                        .addGap(160, 160, 160))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pn)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ap)
                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ce))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(us))
                .addGap(47, 47, 47)
                .addComponent(buscar)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboItemStateChanged
        mostrar_combo();
    }//GEN-LAST:event_comboItemStateChanged

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        buscar();
    }//GEN-LAST:event_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recodar_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recodar_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recodar_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recodar_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recodar_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ap;
    private javax.swing.JTextField apellido;
    private javax.swing.JButton buscar;
    private javax.swing.JLabel ce;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JTextField correo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel pn;
    private javax.swing.JLabel us;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
