/*

* To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisteecle;

import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.awt.Dimension;
import java.awt.Panel;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Jesùs de Gran Poder
 */
public class registro_usuario extends javax.swing.JFrame {

    conexion cc = new conexion();
    Connection cn = cc.conexion();

    public registro_usuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public void Agregar() {

// Variables de consultas y axuliares.
        String pass;
        pass = String.valueOf(contraseña.getPassword());
//Consultas de el metodo agragar...        
        String SQL = "INSERT INTO usuario (usuario ,contra) VALUES (?,?)";
        String SLQ2 = "INSERT INTO persona(id_usu, nombre1, nombre2, apellido1, apellido2, correo, fecha_n) VALUES (?,?,?,?,?,?,?)";
        String select = "SELECT MAX(id_usu) FROM usuario";

        int x = 0;
// Algortimo para registro de Usuario.
        try {
            // Uso de consulta para Validar o no la contraseña del Usuario principal, y hacer nuevo registro de otro.

            Statement p = cn.createStatement();
            ResultSet r = p.executeQuery(select);
            if (r.next()) {
                x = r.getInt(1);
            }
            if (x > 0) {
                JOptionPane.showMessageDialog(null, "¡Ingresar contraseña del Usuario Principal"
                        + ", y permitir el registro del nuevo Usuario!");
                    ocultar_panel1();
                    visualizar_panel2();
                    cancelar.setEnabled(false);
                
            } else {

                try {
                    //Uso de consulta para registro de Usuario
                    PreparedStatement pst = cn.prepareStatement(SQL);
                    pst.setString(1, usuario.getText());
                    pst.setString(2, pass);
                    pst.executeUpdate();

                    Statement st = cn.createStatement();
                    ResultSet rs = st.executeQuery(select);
                    if (rs.next()) {
                        x = rs.getInt(1);
                    }

                    PreparedStatement pst2 = cn.prepareStatement(SLQ2);

                    pst2.setInt(1, x);
                    pst2.setString(2, primer_nombre.getText());
                    pst2.setString(3, segundo_nombre.getText());
                    pst2.setString(4, apellido_paterno.getText());
                    pst2.setString(5, apellido_materno.getText());
                    pst2.setString(6, correo.getText());
                    pst2.setString(7, ((JTextField) fecha.getDateEditor().getUiComponent()).getText());
                    pst2.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Usuario Registrado..");
                    borrar();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error de Registro");
                }
            }

        } catch (Exception r) {

        }

    }

    public void Registro() {
// Variables de consultas y axuliares.
        
        String pass;
        String pass1;
        pass = String.valueOf(contraseña.getPassword());
        pass1 = String.valueOf(contra_adm.getPassword());
        String SQL = "INSERT INTO usuario (usuario ,contra) VALUES (?,?)";
        String SLQ2 = "INSERT INTO persona(id_usu, nombre1, nombre2, apellido1, apellido2, correo, fecha_n) VALUES (?,?,?,?,?,?,?)";
        String select = "SELECT MAX(id_usu) FROM usuario";
        String permitir = " SELECT * FROM usuario WHERE id_usu= 1  AND contra='" + pass1 + "'";
        int resultado = 0;
        int x = 0;

// Algortimo para registro de Usuario.
        try {

            Statement con = cn.createStatement();
            ResultSet r1 = con.executeQuery(permitir);

            if (r1.next()) {
                resultado = 1;

                if (resultado == 1) {
                    PreparedStatement pst = cn.prepareStatement(SQL);
                    pst.setString(1, usuario.getText());
                    pst.setString(2, pass);
                    pst.executeUpdate();

                    Statement st = cn.createStatement();
                    ResultSet rs = st.executeQuery(select);
                    if (rs.next()) {
                        x = rs.getInt(1);
                    }

                    PreparedStatement pst2 = cn.prepareStatement(SLQ2);

                    pst2.setInt(1, x);
                    pst2.setString(2, primer_nombre.getText());
                    pst2.setString(3, segundo_nombre.getText());
                    pst2.setString(4, apellido_paterno.getText());
                    pst2.setString(5, apellido_materno.getText());
                    pst2.setString(6, correo.getText());
                    pst2.setString(7, ((JTextField) fecha.getDateEditor().getUiComponent()).getText());
                    pst2.executeUpdate();
                    JOptionPane.showMessageDialog(null, "USUARIO REGISTRADO");
                    borrar1();
                    borrar();
                    ocultar_panel2();
                    visualizar_panel1();
                    registrar.setEnabled(true);
                    cancelar.setEnabled(true);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Contraseña del Administrador Incorrecta");
            }
        } catch (Exception r) {
            JOptionPane.showMessageDialog(null, "Error de Registro");
        }
    }

    public void borrar() {
        JTextField caja;

        for (int i = 0; i < panel_registro.getComponentCount(); i++) {
            {
                if (panel_registro.getComponent(i).getClass().getName().equals("javax.swing.JTextField")) {
                    caja = (JTextField) panel_registro.getComponent(i);
                    caja.setText("");
                }
            }
        }

        contraseña.setText("");
        Date date = null;
        fecha.setDate(date);
    }

    public void borrar1() {
    }

    public void visualizar_panel1() {
        ;
        //etiquetas
        pn.setEnabled(true);
        sn.setEnabled(true);
        ap.setEnabled(true);
        am.setEnabled(true);
        u.setEnabled(true);
        c.setEnabled(true);
        cor.setEnabled(true);
        fn.setEnabled(true);
        //cajas de texto
        primer_nombre.setEnabled(true);
        segundo_nombre.setEnabled(true);
        apellido_paterno.setEnabled(true);
        apellido_materno.setEnabled(true);
        usuario.setEnabled(true);
        contraseña.setEnabled(true);
        correo.setEnabled(true);
        fecha.setEnabled(true);
    }

    public void ocultar_panel1() {

        //etiquetas
        pn.setEnabled(false);
        sn.setEnabled(false);
        ap.setEnabled(false);
        am.setEnabled(false);
        u.setEnabled(false);
        c.setEnabled(false);
        cor.setEnabled(false);
        fn.setEnabled(false);
        //cajas de texto
        primer_nombre.setEnabled(false);
        segundo_nombre.setEnabled(false);
        apellido_paterno.setEnabled(false);
        apellido_materno.setEnabled(false);
        usuario.setEnabled(false);
        contraseña.setEnabled(false);
        correo.setEnabled(false);
        fecha.setEnabled(false);
    }

    public void visualizar_panel2() {
        panel_permisoadm.setEnabled(true);
         ca.setEnabled(true);
        contra_adm.setEnabled(true);
        //botones
        permitir.setEnabled(true);
        cancelaradm.setEnabled(true);
    }

    public void ocultar_panel2() {
        panel_permisoadm.setEnabled(false);
        ca.setEnabled(false);
        contra_adm.setEnabled(false);
        //botones
        permitir.setEnabled(false);
        cancelaradm.setEnabled(false);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jToggleButton1 = new javax.swing.JToggleButton();
        panel_registro = new javax.swing.JPanel();
        u = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        pn = new javax.swing.JLabel();
        sn = new javax.swing.JLabel();
        primer_nombre = new javax.swing.JTextField();
        segundo_nombre = new javax.swing.JTextField();
        ap = new javax.swing.JLabel();
        am = new javax.swing.JLabel();
        cor = new javax.swing.JLabel();
        fn = new javax.swing.JLabel();
        apellido_paterno = new javax.swing.JTextField();
        apellido_materno = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        contraseña = new javax.swing.JPasswordField();
        fecha = new com.toedter.calendar.JDateChooser();
        panel_permisoadm = new javax.swing.JPanel();
        permitir = new javax.swing.JButton();
        cancelaradm = new javax.swing.JButton();
        ca = new javax.swing.JLabel();
        contra_adm = new javax.swing.JPasswordField();
        registrar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_registro.setBorder(javax.swing.BorderFactory.createTitledBorder("REGISTRO"));
        panel_registro.setToolTipText("");

        u.setText("Usuario");

        c.setText("Contraseña");

        usuario.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                usuarioCaretUpdate(evt);
            }
        });
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });

        pn.setText("Primer Nombre");

        sn.setText("Segundo Nombre");

        primer_nombre.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                primer_nombreCaretUpdate(evt);
            }
        });
        primer_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primer_nombreActionPerformed(evt);
            }
        });

        segundo_nombre.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                segundo_nombreCaretUpdate(evt);
            }
        });

        ap.setText("Apellido Paterno");

        am.setText("Apellido Materno");

        cor.setText("Correo Eléctronico");

        fn.setText("Fecha de Nacimiento");

        apellido_paterno.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                apellido_paternoCaretUpdate(evt);
            }
        });

        apellido_materno.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                apellido_maternoCaretUpdate(evt);
            }
        });

        correo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                correoCaretUpdate(evt);
            }
        });

        contraseña.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                contraseñaCaretUpdate(evt);
            }
        });
        contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaActionPerformed(evt);
            }
        });

        fecha.setDateFormatString("yyyy/MM/dd\n");

        panel_permisoadm.setBorder(javax.swing.BorderFactory.createTitledBorder("PERMISO DE ADMINISTRADOR"));
        panel_permisoadm.setEnabled(false);

        permitir.setText("PERMITIR REGISTRO");
        permitir.setEnabled(false);
        permitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permitirActionPerformed(evt);
            }
        });

        cancelaradm.setText("CANCELAR");
        cancelaradm.setEnabled(false);
        cancelaradm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelaradmActionPerformed(evt);
            }
        });

        ca.setText("Contraseña del Administrador");
        ca.setEnabled(false);

        contra_adm.setEnabled(false);

        javax.swing.GroupLayout panel_permisoadmLayout = new javax.swing.GroupLayout(panel_permisoadm);
        panel_permisoadm.setLayout(panel_permisoadmLayout);
        panel_permisoadmLayout.setHorizontalGroup(
            panel_permisoadmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_permisoadmLayout.createSequentialGroup()
                .addGroup(panel_permisoadmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_permisoadmLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(permitir)
                        .addGap(30, 30, 30)
                        .addComponent(cancelaradm))
                    .addGroup(panel_permisoadmLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(ca)
                        .addGap(18, 18, 18)
                        .addComponent(contra_adm, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        panel_permisoadmLayout.setVerticalGroup(
            panel_permisoadmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_permisoadmLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(panel_permisoadmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ca)
                    .addComponent(contra_adm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_permisoadmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(permitir)
                    .addComponent(cancelaradm))
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_registroLayout = new javax.swing.GroupLayout(panel_registro);
        panel_registro.setLayout(panel_registroLayout);
        panel_registroLayout.setHorizontalGroup(
            panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_registroLayout.createSequentialGroup()
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_registroLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(u)
                            .addGroup(panel_registroLayout.createSequentialGroup()
                                .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(primer_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_registroLayout.createSequentialGroup()
                                .addComponent(am)
                                .addGap(25, 25, 25)
                                .addComponent(apellido_materno, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_registroLayout.createSequentialGroup()
                                .addComponent(c)
                                .addGap(18, 18, 18)
                                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_registroLayout.createSequentialGroup()
                                .addComponent(fn)
                                .addGap(18, 18, 18)
                                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panel_permisoadm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_registroLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sn)
                            .addComponent(ap))
                        .addGap(24, 24, 24)
                        .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(segundo_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(apellido_paterno)))
                    .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panel_registroLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_registroLayout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(cor)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_registroLayout.setVerticalGroup(
            panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_registroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primer_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sn)
                    .addComponent(segundo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ap)
                    .addComponent(apellido_paterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellido_materno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(am))
                .addGap(11, 11, 11)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c)
                    .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cor))
                .addGap(14, 14, 14)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fn)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(panel_permisoadm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        registrar.setText("REGISTRAR");
        registrar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                registrarStateChanged(evt);
            }
        });
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        cancelar.setText("CANCELAR");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registrar)
                    .addComponent(cancelar)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(registrar)
                        .addGap(18, 18, 18)
                        .addComponent(cancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        Agregar();

    }//GEN-LAST:event_registrarActionPerformed

    private void primer_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primer_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_primer_nombreActionPerformed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void permitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permitirActionPerformed
        Registro();

    }//GEN-LAST:event_permitirActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        borrar();


    }//GEN-LAST:event_cancelarActionPerformed

    private void contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaActionPerformed

    private void cancelaradmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelaradmActionPerformed
        borrar1();
        visualizar_panel1();
        registrar.setEnabled(true);
        cancelar.setEnabled(true);
        ocultar_panel2();

    }//GEN-LAST:event_cancelaradmActionPerformed

    private void registrarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_registrarStateChanged


    }//GEN-LAST:event_registrarStateChanged

    private void primer_nombreCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_primer_nombreCaretUpdate
    }//GEN-LAST:event_primer_nombreCaretUpdate

    private void segundo_nombreCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_segundo_nombreCaretUpdate
    }//GEN-LAST:event_segundo_nombreCaretUpdate

    private void apellido_paternoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_apellido_paternoCaretUpdate
    }//GEN-LAST:event_apellido_paternoCaretUpdate

    private void apellido_maternoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_apellido_maternoCaretUpdate
    }//GEN-LAST:event_apellido_maternoCaretUpdate

    private void usuarioCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_usuarioCaretUpdate
    }//GEN-LAST:event_usuarioCaretUpdate

    private void contraseñaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_contraseñaCaretUpdate
    }//GEN-LAST:event_contraseñaCaretUpdate

    private void correoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_correoCaretUpdate

    }//GEN-LAST:event_correoCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro_usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel am;
    private javax.swing.JLabel ap;
    private javax.swing.JTextField apellido_materno;
    private javax.swing.JTextField apellido_paterno;
    private javax.swing.JLabel c;
    private javax.swing.JLabel ca;
    public static javax.swing.JButton cancelar;
    public static javax.swing.JButton cancelaradm;
    private javax.swing.JPasswordField contra_adm;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JLabel cor;
    private javax.swing.JTextField correo;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel fn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton jToggleButton1;
    public static javax.swing.JPanel panel_permisoadm;
    private javax.swing.JPanel panel_registro;
    public static javax.swing.JButton permitir;
    private javax.swing.JLabel pn;
    private javax.swing.JTextField primer_nombre;
    public static javax.swing.JButton registrar;
    private javax.swing.JTextField segundo_nombre;
    private javax.swing.JLabel sn;
    private javax.swing.JLabel u;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
